import { build } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../../', import.meta.url));
const check = process.argv.includes('--check');
for (const [entry, output] of [['admin', 'app'], ['client', 'client']]) {
  const result = await build({
    absWorkingDir: root,
    entryPoints: [`frontend/src/${entry}.jsx`],
    outfile: `src/print_appliance/static/${output}.js`,
    bundle: true, minify: true, write: false, sourcemap: false,
    jsx: 'automatic', target: ['es2020'], legalComments: 'inline',
    define: { 'process.env.NODE_ENV': '"production"' },
    banner: { js: '// Generated by npm run build. Edit frontend/src, not this file.' },
  });
  for (const file of result.outputFiles) await emit(file.path, file.text);
}
let licenses = 'Bundled offline UI runtime licenses (React, React DOM, Scheduler)\n';
for (const name of ['react', 'react-dom', 'scheduler']) {
  licenses += `\n--- ${name} ---\n` + await readFile(path.join(root, 'node_modules', name, 'LICENSE'), 'utf8');
}
await emit(path.join(root, 'src/print_appliance/static/THIRD_PARTY_LICENSES.txt'), licenses);
console.log(check ? 'Offline bundles match JSX sources.' : 'Built offline admin/client React bundles.');
async function emit(filename, content) {
  if (check) {
    if (await readFile(filename, 'utf8') !== content) throw new Error(`${path.relative(root, filename)} is stale; run npm run build`);
  } else await writeFile(filename, content);
}
